"""finished models with relationships

Revision ID: 7117d2edda67
Revises: 97a18e58ced4
Create Date: 2023-12-12 23:33:32.421340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7117d2edda67'
down_revision = '97a18e58ced4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('workout_details', sa.String(), nullable=True),
    sa.Column('workout_difficulty', sa.String(), nullable=True),
    sa.Column('workout_type', sa.String(), nullable=True),
    sa.Column('workout_category', sa.String(), nullable=True),
    sa.Column('workout_likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('comment_likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_comments_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_favorites_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('workouts')
    # ### end Alembic commands ###
