"""removed comment likes column

Revision ID: b012ebc6e285
Revises: cdeab4832c35
Create Date: 2023-12-19 02:25:45.551762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b012ebc6e285'
down_revision = 'cdeab4832c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('comment_likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_likes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
