"""added new user columns and workout title column

Revision ID: cdeab4832c35
Revises: 7117d2edda67
Create Date: 2023-12-18 21:04:23.549585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdeab4832c35'
down_revision = '7117d2edda67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parentId', sa.Integer(), nullable=True))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('workout_name')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('parentId')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
